version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/dbname
    volumes:
      - ./api:/app
      - ./shared:/app/shared

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    command: rq worker --with-scheduler
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://user:password@db/dbname
    volumes:
      - ./worker:/app
      - ./shared:/app/shared

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  test:
      build:
        context: .
        dockerfile: test/Dockerfile
      volumes:
        - .:/app
      depends_on:
        - db

volumes:
  db-data:
